name: Test roles

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Enter 'force' if you want to force a refresh"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@master
     # 1st
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.run_id }}
      - name: get-caller-identity
        run: |
          mkdir -p ~/.aws
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          aws --version
          aws sts get-caller-identity
          aws configure list
          aws configure list-profiles
      - name: Copy from S3
        run: |
          aws s3 sync s3://kyoninja-bucket/terraform.tfstate .
          aws s3 sync main.tf s3://kyoninja-bucket
          ls -la
      # 2nd
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@master
      #   with:
      #     aws-region: us-east-1
      #     role-to-assume: arn:aws:iam::123456789012:role/myrole_B
      #     role-session-name: GitHubActions-${{ github.run_id }}
      # - name: get-caller-identity shows myrole_B as expected
      #   run: aws sts get-caller-identity